services:
  - type: web
    name: madvision-demo
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo 'export PATH=$PATH:~/.local/bin' >> ~/.bashrc
    startCommand: streamlit run app2.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
